### ISSUE TITLE
hydra: DSN should be excluded from the configmap

### ISSUE THREAD

**Issue by paulbdavis** [ory/k8s#75] opened 2019-10-28 23:38 UTC
**Describe the bug**

The DSN definition is making it's way into the configmap while the value is being consumed via the secretRef env configuration. This is in the hydra chart (though I have not tested the other charts yet)

**To Reproduce**

Install the chart as normal

**Expected behavior**

I would expect the DSN to only be stored in the secret that is set up

**Environment**

chart version 0.0.42

**Comment by aeneasr** [comment] 2019-10-29 10:47
Thank you for the report, closing because this is a dupe of: #47

**Closed by aeneasr** 2019-10-29 10:47 UTC
