### ISSUE TITLE
Hydra Maester always deploys into the detault namespace 

### ISSUE THREAD

**Issue by alexivkin** [ory/k8s#224] opened 2021-02-19 22:16 UTC
Setting namespace via helm `--namespace=` has no effect on hydra-maester. The culprit seems to be a missing "namespace" definition in the metadata section of helm/charts/hydra-maester/templates/deployment.yaml

**Comment by Demonsthere** [comment] 2021-05-24 15:48
When installing by helm, the namespace should be controlled by helm itself. I could not reproduce the issue:

```bash
helm install hydra-maester ./helm/charts/hydra-maester -f local/hydra-maester.yaml --namespace foo
NAME: hydra-maester
LAST DEPLOYED: Mon May 24 17:46:11 2021
NAMESPACE: foo
STATUS: deployed
REVISION: 1
TEST SUITE: None

kubectl get all -n default
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   4m15s

kubectl get all -n foo
NAME                                 READY   STATUS             RESTARTS   AGE
pod/hydra-maester-78b7cd8867-hl8lc   0/1     CrashLoopBackOff   4          110s

NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hydra-maester   0/1     1            0           110s

NAME                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/hydra-maester-78b7cd8867   1         1         0       110s
```

Do you deploy it with some automation tool and not the helm binary?

**Comment by aeneasr** [comment] 2021-05-27 15:44
Closing as can't reproduce. If still an issue, feel free to reopen :)

**Closed by aeneasr** 2021-05-27 15:44 UTC
Labels: good first issue, help wanted
